const courses = [
    {
        id: 'CSE101',
        title: 'Introduction to Data Science',
        department: 'CSE',
        level: 'undergraduate',
        credits: 3,
        instructor: 'Dr. KimAng',
        semester: 'fall',
    },
    {
        id: 'CSE201',
        title: 'Data Structures',
        department: 'CSE',
        level: 'undergraduate',
        credits: 4,
        instructor: 'Dr. Lee',
        semester: 'spring',
    },
    {
        id: 'CSE501',
        title: 'Advanced Algorithms',
        department: 'CSE',
        level: 'graduate',
        credits: 3,
        instructor: 'Dr. Smith',
        semester: 'fall',
    },
    {
        id: 'ECE101',
        title: 'Circuits and Systems',
        department: 'ECE',
        level: 'undergraduate',
        credits: 3,
        instructor: 'Dr. Patel',
        semester: 'fall',
    },
    {
        id: 'ECE301',
        title: 'Digital Signal Processing',
        department: 'ECE',
        level: 'undergraduate',
        credits: 4,
        instructor: 'Dr. Sharma',
        semester: 'spring',
    },
    {
        id: 'MATH101',
        title: 'Calculus I',
        department: 'MATH',
        level: 'undergraduate',
        credits: 3,
        instructor: 'Dr. Nguyen',
        semester: 'fall',
    },
    {
        id: 'MATH501',
        title: 'Real Analysis',
        department: 'MATH',
        level: 'graduate',
        credits: 4,
        instructor: 'Dr. Kumar',
        semester: 'spring',
    },
    {
        id: 'PHY201',
        title: 'Electromagnetism',
        department: 'PHYS',
        level: 'undergraduate',
        credits: 3,
        instructor: 'Dr. Johnson',
        semester: 'fall',
    },
    {
        id: 'PHY601',
        title: 'Quantum Mechanics',
        department: 'PHYS',
        level: 'graduate',
        credits: 4,
        instructor: 'Dr. Zhang',
        semester: 'spring',
    }
];

export default courses;
